sudo: false
language: php
php:
  - 5.5
  - 7.1

before_script:
  # Git clone the Drupal 8.5.x repo, so that we can apply patches to it.
  - git clone --branch 8.5.x https://git.drupal.org/project/drupal.git
  # Apply patch. You only get one.
  - cd drupal
  - git apply ../patch/fixes.patch
  - cd ..
  # Copy the tests out of core.
  - cp -R drupal/core/tests .
  - test -f tests/Drupal/Tests/UnitTestCase.php

script:
  # Install our components through composer, getting lowest versions possible.
  - composer update --prefer-lowest --no-progress
  # We currently don't use core's phpunit.xml.dist or bootstrap.php. This is
  # because there are a lot of dependencies in there that won't be available to
  # us. As core gets better at this, we'll need to change this invocation.
  - ./vendor/bin/phpunit --bootstrap bootstrap.php tests/Drupal/Tests/Component/
  # Install our components with the highest possible.
  - composer update --no-progress
  # Repeat the tests.
  - ./vendor/bin/phpunit --bootstrap bootstrap.php tests/Drupal/Tests/Component/
