sudo: false
language: php
php:
  - 5.5
  - 7.1

before_script:
  # Git clone the Drupal 8.5.x repo, so that we can apply patches to it.
  - git clone --branch 8.5.x https://git.drupal.org/project/drupal.git
  # DL and apply patches.
  # Copy the tests out of core.
  - cp -R drupal/core/tests .
  - test -f tests/Drupal/Tests/UnitTestCase.php
  # Install our components through composer.
  - composer update --no-progress --no-suggest

script:
  # We currently don't use core's phpunit.xml.dist or bootstrap.php. This is
  # because there are a lot of dependencies in there that won't be available to
  # us. As core gets better at this, we'll need to change this invocation.
  - ./vendor/bin/phpunit --bootstrap bootstrap.php tests/Drupal/Tests/Component/
